#Prgramming language used
language: python
#Language version
python:
  - "3.6"

env:
  global:
  - SECRET_KEY=hii-inafaa-kua-siri
  - DATABASE_URL="postgres://testuser:password@localhost:5432/politico_test_db"

before_script:
  - psql -c 'create database politico_test_db;' -U postgres
  - psql -c "create user testuser with PASSWORD 'password';" -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter

#installing requirements on travis
install:
- pip install -r requirements.txt
- pip install coveralls
- pip install codeclimate-test-reporter

# command to run tests
script:
  - pytest --cov-report term-missing --cov=app

#code to run after tests
after_success:
  - coveralls
  - codeclimate-test-reporter